export const DATA_TO_SHOW = [
  ["title2", "Three mayor tasks of a CEO are: talent, capital and vision in a company. "],
  ["title2", "Talent"],
  [
    "content",
    [
      "Talent is hire and fire. Hold a high density of talent inside the company, contract the right person for the mission and fire quickly the person who don't work. With the mentality before startups, where people work in the same company for forty or thirty years, exist the perception of fire or get fired is the worst thing you can do or receive. This is a wrong perception. In TI, get fired is not a judgement of your talent (except if you are a bad person doing your job, but almost never is this). Companies fit with some type of talent, this consider: culture, the ways they react in the momento of the life, sometimes some people will not fit in that culture and maybe you can be happier in other place. The bad thing here is some people take decisions more for the fear of lost than the joy of win.",
      "Some times the compassionate decision of the executive layer of the company is take the decision of fire some persons, because they will be happier and better in other places. Remember your job is what you do the mayor part of the time when the sun is in the skyies and your adult life, in your most productive stage. Some people have a job for the money, this is something common but if you can do a job doing what you like, do you imagine that?",
      "Having said that, the stigma of fire is unfair, because what it really is, is the start of a new beginning. The stigma is not free because there is examples on the crisis when people get fired and ends without economic possibilities to affort the most basic things for themself or they loved ones. This in the TI does not happen because exist ten to twenty times more demand of talent that the talent that actually exists. This will continue even in a recession."
    ]
  ],
  ["title2", "Capital"],
  [
    "content",
    [
      "Raise up inversion and sell. This mean the bank account has money. Companies don't died when the founders died, when a huge reccession is on the corner, or in the middle of a war, companies die when the money run out on the bank accounts. With no money you cannot operate. The money run out on the bank account when you don't have inversion to keep growing or when you are not selling (and you dont have cash flow). With this the company exist.",
      "Is work of the CEO define how to get the money: company should be public and go public (making an IPO)? Should sell actions? Should make key inversions? Or just have to create, launch and sell new products?"
    ]
  ],
  ["title2", "Vision"],
  [
    "content",
    [
      "This is basically define the course of the company.",
      "Let's see come CEO that change the course of the company:",
      "1) Mark Zuckerberg, CEO of META (before Feacebook). Now the path of the company will be to the metaverse. In the process a bunch of executive are quit including the Chief Operator Officer: Sheryl Kara Sandberg one of the most poweful, popular and talented of Sillicon Valley.",
      "2) Susan Wojcicki, CEO of youtube. Her vision for the company is: Youtube have to reward and support creators. This means the creation of 'Mr Beast', 'Kardashan' and other artists, influencers, youtubers, gamers and so on. They focus in creators so that they can live of his creations.",
      "3) Ellen Pao was for a time the CEO of reddit. She tried to change the direction of the company but didn't work. The change was to a more humanist perspective, control, moderating active and pro active way the more problematics subredits and reddit community that was so toxic. What she got was one of the most aggresive and and destructive reactions of the internet history. She end lefting the company. With time all the things of the vision that Ellen Pao propose was introduced in reddit, but in slow steps, not fast steps. In this way toxic peoepl in the community didn't get notice.",
      "4) Whitney Wolfe Herd, one case of success. She is the CEO of Bumble, a date app. The interest thing here is the pro activity is in hands of the womans and not mens. This is the inovation. Compared to match.com, tinder, and so on. This allow to bumble, in a satured market with so many options, be more effective with a much more trustworthy brand for the business of loneliness and flesh. With this they go public, creating a wonderful company because the correct vision."
    ]
  ],
  ["title2", "Personal characteristic of CEO's "],
  ["title3", "Be a bottleneck and learn how to manage their time"],
  [
    "content",
    [
      "If the CEO don't take this decisions her/his is a bottleneck. The most problematic bottleneck in the company is the indecision of the executive layer, of the CEO. For this reason one of the mayor things that a CEO have to know is how to manage his time: the schedule have to be impeccable, never arrive late for meetings (no 15 minutes later, no 30 minutes late), always fulfill all the things you have to do in the best way possible. If the CEO don't do this you will get a domino effect, where the thing that happend in the morning affect the things in the afternoon. So, in this sense the CEO transform himself in the biggest bottleneck."
    ]
  ],
  ['title3', 'Be carefull: CEO are always the most strongest voice in the company'],
  ['content', ["This is so even if the CEO is wrong, what the CEO say is the thing the people tends to do. Even if the CEO don't want to lead with authority what happend is in the process the authority is delegated to someone else. The thing here is very few persons have the bravery/courage, knowledge, fortitude or experience to contradict him. And when someone have a contradict opinion, the CEO need to show or develop the bravey/courage, knowledge, fortitue and experience to leave people make mistakes, sometimes huges and big mistakes. In this case is interest how much confidence develop the CEO in a cultural level to allow people contradict him, in a personal level: which was the consequences of a opposite opinion the last time; in a company level: which was the consequences for other people get a opposite opinion to the CEO. The most effective way to grow is making mistakes (persons learn with trial and error, not trial and sucess), growth in a professional way is face with data, rationality and compassion (this last one is very important) the executive layer of the company.", "The reality with the above when is done, rarely have negative effects or nothing can happen. If you face negative effect for this and get fired that's something good because you was in the wrong company. But if in this opposite opinion to the executive layer with data, rationality and compassion, the person was right, that is a deep source professional and personal growth. In this way person get more responsability and more force.", "At the end of the day CEO are the visible face or the spokesmen of the company. Here the CEO's are very differents, for example compare Timothy Donald Cook and Steven Paul Jobs in the handling of the press. Apple has grown more than ever under the direction of Timothy Dinald Cook. Steven was more skilled in front of the press and this is more valuable in other stage of the company, for example when people are more skeptical of the company. Timothy handle a company where people don't buy their products for the price, not for the quality. So, CEO are different depending of the stage of the company but they will be the visible face, whether they like it or not."],],
  ['title3', "CEO's talks with users and create the product"],
  ['content', ["Good CEO's talks with their users and with the feedback create a product. With that product they talk again with users. This is the virtuous circle almost all companies, not all of them. This because some companies sell services. But in general companies have clients and that clients recieve a product or service, the work of who lead the company is talk with that user to create a product. A classic error in this sense is delegate this conversation, information and feedback to a team of market research. This teams are valuable but they have their own perspective. This is not a substitute of a conversation in real time with a user and with this feedback create product.", "I recommend this course of Platzi (is in spanish): 'Course of technology for managers and directors' (https://platzi.com/cursos/tecnologia-gerentes/)"],],
  ['title3', 'Learn to make quick decisions even if they are wrong'],
  ['content', ["When you are the CEO the indecision of the company ends in the CEO. The indecision is something that if someone are not solve that yet you have to make the decision at the end, always. The CEO can do nothing for this, what happen in this situation? The problem will keep rising and making consequences to the company. How a CEO solve this problems: they make quick decisions, now. A quick decision is always better than the indecision. Even a bas decision is best than a indecision.", "Having said that, what is indecision? Fear to something. In perspective: the emotion to lose is greater than the emotion to win.", "Why a bad decision is better than a indecision, because with action (even if is a bad decision) you can have more data and with more data you can make decision with more information for the path of the company.", "The indecision is no-action, is the status quo. Companies that are not growing are dying because the rest of the companies are growing.", "How to make good quick decisions? Developing your instinct and you can develop this with good data. One of the fundamental labors of the CEO is understand the metric of the company.", "Today, any person in any part of the company should be able to know how the company is doing, only with one click. This is more relevant for the Chief Executive Officer. And to know which is the correct metric, you have to learn about the so call North Star Metric.", "Platzi have a couse for this, is in spanish: https://platzi.com/cursos/north-star-metric-startup/"],],
  ['title3', 'Manage persons from who you have responsabilities: the so call stakeholders'],
  ['content', ["All this people invest something in the company. Tipical ones are: users/clients (this are the people who use the service/product), employees (who build the service/product ) and investors (people who put the money to this service/product exist).", "Every one of this stakeholders function in a different way. Let's think in a public education, of this three stakeholder who are the most importante people. From most to least important: professors, fathers and students. In this same order of importancy, for company is: clients/users, employees and investors. The investors are not the most important thing because the growh of the companies come from the users/clients, not investors."],],
  ['title3', 'You are an expert in your market'],
  ['content', ["This means you know as much as you can about your product/service, the market, the history and any other thing that is related with that. This is become a expert, a nerd let say. If you are not this type of person, why are you doing this thing in the first place? The very first step to become a CEO is have a intellectual curiosity as powerful as the big bang, being more concrete: you have to be insufferable with your knowledge and what you do."],],
  ['title3', "You do whatever that it's needed in the moment"],
  ['content', ["For example, when the production line of the model 3 in Tesla (best selling car), Elons Musk went to live to the factory. When Space X rockets explode constantly before land up, Elon Musk wen to live to Space X factory. This mean pay attention, use your time and be in the place where the things are happening, where the problem exist. When the iPhone 4 or iPhone 5 have problem with the antennas Steve Job and Tim Cock went to China to know what is happening.", `"You do whatever it's needed in the moment": your team have to eat and the food is not in the table, so you have to go for food. Obviusly, the things that allow the company growth.`],],
  ['title3', 'What happen to you, will happen to the company'],
  ['content', ["This in the sense of mental and body health. People see in the CEO the solidity, risk and the uncertainty. One of the labor of the CEO is absorb the uncertainty to allow all the people make their best work. This mean that the CEO have to take care about his diet, his food, his water, is exercise, the interpersonal relationships, psychological therapy, couching, good sleep and any other thing related with your body and mental health (saying in other way: any thing that is related with health, happiness and strong).", "Don't work the burn out beeing CEO."],],
  ['title2', 'Last tip'],
  ['content', ["Your time is not yours, belongs to your team. And never is 'too valuable' to share it with your team. In your team you have the most valuable return of your time, when you sit with them to make mentorship, to create new things. Never your time is 'too valuable' to share it with your team."],],
]
