export const DATA_TO_SHOW = [
  [
    "content",
    [
      `A question to Pablo González: the day someone said to you "your company is a unicorn in Latin America", what do you felt about that? What inside of you came more alive and what died at that moment? The answer Pablo Gonzáles was: "In the beggining we born with the goal of accomplish our mision «Abilitate case of use of crypto in Latin America», we never make our measure of success in a evaluation or the money we can lift. In the beggining I think «we need a roadmap, how much capital we going to need, in which years we going to lift and so on» but was imposible to create this because the market has change. We can make proyections but is hard. So much of our growh as come from the growth of Crypto itself. So, we have never had a roadmpa «Wen the company lift this ammount of money we going to do this and that or when we lift certain amount we have ben in the top». When we have the category of unicorn is a amazing evaluation because we came the biggest company of the country, but at the same time is weird because people around you (of the same team or other people) think «Oh, so, with that amount of money and category, you are done, right? There is no more after that» but in my head (said Pablo) this is just the beggining, we don't even start. Is important to recognice and celebrate the success but still is weird this type of success".`,
      `A question to Pablo Gonzáles: is for sure you pass for dificult moments when you have little money in the bank, how do you lift on those situations, how do you push the team, was something natural to you, to your parteners? Because in the path of the entrepreneur the things always become hard what advice do you do for people who is starting in this, because you already know how to deal with this things. From Pablo Gonzáles: the most important is have a belief based on fundments to where we going as humanity or society, which is going to be te tendency and stand firm on it. One of the bad characteristic that Pablo and their partners have is that they are very stubborn because a thousand times they could say "okay, that was fun, we learn a lot but now we have to come back to reality. One little history: at some point we manage money from the users and for the bank the money on the bank was zero and I think "what brought me here, at this point in my life", I would like to be the taxist, the person who sell anything in the streets, anyone less me. At some point we fix that and we learn to not depend of third ones". So, te question here is "why a person is going to live all this stresful things" and the reason for that is the mision, the goal, the objective of the company, that gives you an extra fuel when you think you can't do more.`,
      `A question: in ten years more, when all the people understand your product or service, what you are going to do in that moment? From Pablo Gonzáles he said that at some point the actuallity will determine the next move. For example when internet arrive so much people imagine which things they can do with that, so many of them will make real and others are not real yet. So, is the same: the problems you solve will point the next problem you have to solve.`,
      `Nowadays, no matter is you are a entrepreneur or other type of person, you have to be prepare to re invented yourself all the time. `,
      `And advice frrom Pablo Gonzáles is: the best way to learn things is doing it, but try to use little capital.`
    ]
  ]
]
