export const DATA_TO_SHOW = [
  [
    "content",
    [
      `A question: what is the worst to be the number one in something, to be the first person to innovate at some field and therefore make all the mistakes? From Jonathan Lewy he said: first, when you do something you don't think that you are the first and therefore it's the worst. As a entrepeneur you only see something and you want to do that, if you could know all the difficulties in advance probably you wouldn't do it.`,
      `From the perspective of Jonathan Lewy, be a entrepreneur is more difficult than be a investor. Both have their own difficulties but in the building of companies the Founders and CEO have everything in only one company.`,
      `In Latin America make sense to hire so much people because they are cheaper than workers of United States (words of Jonathan Lewy).`,
      `To much people think that investors have money. Investor do inversions but not always with their own money, normally they invest the money of someone else. Another mistake is consider the investors like a evil person who want to control the company. A question for Jonathan Lewy: which another wrong idea people have on the inversion industry in tech? First is understand why this investor do their invests, is different a Venture Capital (that use money of others, their obligation is make the best for their investors. Is not something good or bad, is just their obligations. So, in this point some times what is better for the company is not the best for the investors, and viceversa). This things usually don't get protagonism, but is important that everyone is aligned with the company.`,
      `In the companies, the important things are: speed of executions, acces to capital (to execute the idea).`,
      `A question: how it feels from the inside pass from a start a company from scratch to have a multi billion company? From Jonatahn Lewy: when you are there you don't think too much about that, you have focus on the problems: more growth mean more problems to solve. The price of this is have a full time compromise and be all time the busy.`,
      `Raise capital is something that never ends: when you finish one round the have to start the follow.`,
      `There is a saying in the tech industry: hardware is hard. This is true for all the players because have a high barrier of entry.`,
      `In general, when you solve one problem one or more problems will emerge after that.`,
      `A question to reflect about the past: which things would you do different with the company?`,
      `A question: every start up wants to grow but which are the signs that you are growing in a unhealthy way? For Jonathan Lewy, he said: every context is different and year by year things change, so be aware of this is important. The second thing is just thinking about the pros and cons of your business: what is better for the company and which are the benefit cost of the decisions you have to make.`,
      `A question: which things for people who start business would be very good they know but in general they don't incorporate that information until they get suffer from that. Which thing would be? For Jonathan Lewy, he said: every founder and CEO make common mistakes (for this exist YComabinator and others to catch all this things) but what you have to know is this 'is your companny and is your decision and no one knows better this company than you. You will have a lot of investors who say to you «do this, and do that» but you will start to lose the north when you start to hear the opinion of someone else above yours. Is something good to ask for advice but always keep it mind that is a help to you make your the best decision, not to do what they tell you. The most you advance will be more difficult because you will start to have a Board of Directors and you will need votes, like a politician. Nonetheles: fight, your goald is fight for what is better for the company'. Third advice: never take decision driven by fear, in this cases you always miss. Take decisions because you think that is the best for the company.`,
      `A question: how to recognize a decision driven by fear and how to avoid that? By Jonathan Lew he said: is something hard, you have to be honest with yourselff and make the difficult questions to you "are you making this decision because you really think is a good decision for the company or because you want to take away a fear?". This is something very personal.`,
      `A question to the past (a reflection): you would start a business again, this business? The question here was made to Jonathan Lewy for the 2600 employee he has and his answer was: yes but the difficult thing here was not the amount of people was the speed of grow, because the culture is very important and develop the culture you want takes time. This is the reason because in United Stated said: hire slow, fire fast. So, take your time to hire the correct people. The culture is alive, not because you believe in the culture people around you will understand and live that culture in the same way, the best way to cultivate culture in others is with the daily rutine in the company, at the end this have a huge impact. A person who don't fit in the culture can have a very negative impact. More people in the company more is diluted the culture in the company, because every new person add something to that culture.`,
      `A question to the past (a reflection): what you don't want to do again? Fuse two teams because the culture, language and other things of boths.`,
      `At the end the main reason to start a business is want to work where the problems are.`,
      `An advice for who wants to start a start up or just have a good job in IT, from Jonathan Lewy: "Don't say this to your parents but you don't need school to be start a startup, instead work for an start up that have lifted, at most, series A to work close with the founder or founders, to see what is good, what is bad to be a founder and how is the path. Plus: work in something that you have interest and if you can be close to founders will be very good to have the experience and not be a one more employee".`
    ]
  ]
]
