export const DATA_TO_SHOW = [
  [
    "content",
    [
      `For start a business is a good thing have certain amount of ignorance or inocence, because if you know all the things in advance (all the strugle and all the difficulties) maybe so many pople will just not start a business at all. For Diego Pachama, he said: this is an advantage of start ups because expert know what can go wrong, so when you have an idea you have to go with experts (this was already tried before, this can be wrong for this and this) but you always have to keep your idea and your vision with innocence.`,
      `How to learn make a growfunding? For the experience of Diego Pachama he said: we make a team and make the homework, we study all the successful project which rise more than one millon of dollars. We se what have in common, take notes and apply those lessons. One of those things was make a viral video that in less than two minutes tell you the idea and people want to say "I want to be part of this".`,
      `In the path of have a company and make it success so many things can happen: you can lift capital and after run out of many, you can go to meet investors and get reject (and for policies of the country you can be involved a deportation process), you can have a good product that, for some reason, goverment or other entities ban. So, the question here is: how a CEO a Founder can go trought all this things, how can you recover of all this things and not only be in bed crying? From the perspective of Diego Pachama he said: there is things that help but one of them are persistence, a warrior spirit where give up is not an option. Other very important things that help is: meditation, personal work is that truly gives you resilience, have a good web of family and friends who gives you affection. Also Buddhism as philosophy not religion, have so much widsom that help you overcome challenges. The thing with this is have a personal philosphy that help you to process all the things that happen. As Diego Pachama said, meditate is like "defragment the hard drive", is the analogy.`,
      `Is ease to resume in two lines something that is correct but doesn't tell all the true. This is often seen in news: "Mary Jean, founder of Very Badass Company, gets public and raised more money than Microsoft did in its first 24 hours". The complete story have more ups and downs.`,
      `In general is a good thing not lose energy, time and attention discussing why the idea of the company is valuable with people who are against that idea or the values of the company. An example: climate change. The world have to do something about that, it is not open to discussion, the questions are how to resolve that, not if is a problem or not. So, an advice here is: you can ignore the information who are against your idea or your values in the company or you can fight them. It is your choice what is better for you.`,
      `Today is a competitive advantage be able to hire people around the world, have their own challenges like the time zone, the use of different tools like Slack, Notion, Asana and maybe others.`,
      `A question to Diego Pachama: how to start in meditation? Diego has the opportunity to have two weeks free and go to Tailand to a Buddhism temple. For a person who not have the time or the money to go to those places, what can do? The answer of Diego Pachama was: dedicate to something that make solutions and not problems. Work for something that it worth, this help with motivation, with creating something bigger than us. This is the first element of resilience to have a life with meaning. For Fred Kofman he said: we have to change from "winning" to "meaning". Second thing: don't obsess with job, the job isn't everything. The job should be for you family and community but if you cannot be with your family and community it's something you are doing bad. Third, work on yourself, on your spirituality, philosophy, values, principles as you want to call them: read books, talk with people, see videos on youtube. And for meditation, on youtube you have all the guru's that exist, you can try different apps too. Other advice from Diego Pachama: live from a gratitude perspective, only to be alive.`
    ]
  ]
]
