export const DATA_TO_SHOW = [
  [
    "content",
    [
      `You have to know the rules of the game you play, if you ignore them intentionally or unintentionally everything can ends quickly.`,
      `A question: which are the advantages of your environment: cultural, economic, opportunity, other that don't have other environments?`,
      `Vivianne Bernardes have a tesis of inversion, paraphrasing Vivianne: "We invest not only in the technology that make revenue growth but also in the technology that make something good to the people, wellbeing, personal growth".`,
      `A question: in the history if your company, in which part of that history you faced the real and close possibility of have to close the company? This is means something that can literally close the company, for internal or external factors.`,
      `A question: sometimes, when you have to keep updated with the change of the environment, you have to fight against your own products, this means make a product or service that compete with other products that you already have and works. This means "cannibalize yourself". With this said, a question: How is it to tell all the people who have already worked on a product that what they have done should no longer be done? The cultural change is the most difficult to move from one team to other team. In this change some people will refuse to change. An example of this type of change: Netflix. They burn all their dvd factories to make all the content in online streaming of other people, to this team they burn all too when they want to make Netflix Original (this make the other content distributors to leave). In other words: Netflix has deleted his own company two times to growth from ashes. The question here is: how do you convince the rebel team that this is the correct idea? You have the team that adapt and therefore they keep going, and you will lose people, no doubt. This means, not always some company are suitable for everybody and when your recognize this you gotta let some people go. This is something normal. The truly compasion is not hold back some people, is fire them (so that they have the opportunity to growth in other place). Is very hard fire people, is one of the hardest things as CEO, as Founder.`,
      `A question: what excites you about the future, the current trajectory of economics, technology, science, ideas and others that the world is on right now? From the perspective of Vivianne Bernardes she said that technology should serve to humans being and not the other way around to liberate the mental capacity of all people who are occupied right now in survive and not create the future. We all have to understand that we are in the same ship. The technology efforts should serve to a general purpose.`,
      `A question: derived from the last question, what do you concern about the actual path in the differents fields: economics, technology, etcetera? From the perspective of Vivianne Bernardes said that she is concerned about the speed of learning of people who is get replaced for the technology, therefore the benefits of technology could arrieve later for people who cannot addapt at the same speed of the changes of technology.`,
      `Today we have some oppotunities to make more harmless mistakes than before in technology. The advice here is to take those opportunities to make those mistakes, you can learn in every place with a computer (desktop, tablet, phone, watch or other device) and a conexion to internet or enough memory.`,
      `Learn is eternal.`
    ]
  ]
]
