export const DATA_TO_SHOW = [
  [
    "content",
    [
      `Is important to take decisions without hear the unproductive fear (you can do this asking yourself "which is the worst that can happen" and with that question and your imagination go to the last crazy consequences. After that make another question to you: is that possible? And if is possible how probable is that?). Aversion to fear is a common characteristic in founders (this is a good thing if guides you to accomplish your goals in a ethic way, is not a good thing if you use this to achieve your goals whatever it takes, even the physical, mental, economic or social health to yourself or others).`,
      "Parents who allow their children make mistakes, even huge mistakes, have a huge impact in that new persons. Allowing children to make mistakes and to feel safe with that is called psychological safety.",
      "The thing with start ups is through the stock options, through the exponential growth, if the company will make excelent, the next job that people inside the company will take is for willing, because they want, not for neccessity. In other words, you can become rich as employee working inside a startup is everything is doing excelent. This happened with AirBnB (the IPO was so well, that for the first 600 employee they achieve billions dollars fortunes).",
      `As Pamela Valdés said: "in a world of the machine learning, the only way to keep relevant is convert yourself in a learning machine, do not stop learning".`,
      `Other sentence: "listening is the new reading" (because she talk about her company: https://www.beek.io)`,
      `If Founders are not the north, the guide of the company, the company will fall. So, one of the works of founders is be well from a physical, mental, emotional, social, sexual, spiritual and others ways.`,
      `Learn how to learn improve your personal security and it takes away the anxiety to not understand the things, because at mayor knowledge of how the things work, your life is easier.`,
      `Paraphrasing Pamela: "I'm never think i'm a woman CEO or a woman Founder or that it's hard to raise capital, i just do things without any limiting beliefs".`,
      `Raise capital is hard. It's difficult to have and transmit the same energy in the speech number 5 than the speech number 120.`,
      `When co-Founder canot continue working togheter they have to understand what thing is something personal and what thing is something about the company. They have to make a clear dividing line where begins and ends one and other. They can save friendships if they want and have one, but it's hard.`,
      `A question: how do you see the future? Founders live in a constant future vision, to build it, betting it's the correct vision and people want to pay for it.`,
      `Money is a multiplier of the things you already have or you already are. If you like to give, you are going to give more, if you want to receive or take away, you going to do more of that when you have money. This explain why some people who won the lottery lose the money after some years or destroy their lives in different ways. Bill Gait said one time: "At some point, money stop to impact your life in a positive way". For example, in Latin America, beyond 50 or 60 thousand of dollar a year the quality of life don't get better for get more money. Same happen in USA from 160 or 170 thoursand of dollars a year. In Europe this starts at 100 thousand dollarrs a year. This happen because people will get less time for themselves. At some point people could buy anything but if they don't have time they will cannot consume in a appropriate way those things. Or even if they have the time: food don't taste better for a rich person then a person who simple can buy the same food.`,
      `A question for Founders and CEO: what you going to do after the company you are running right now or the company you want to start in the future? Probably you are going to live until 100, 120 years or at least 60, 80 years. This question is for the next thing you want to achieve, maybe after 10 years, 20 years or next 20 months. Which thing you want to achieve in your life beside your company?`,
      `One of the components to be happy is your relation with your family. As humans we have two families: the one you are born into and the one you crate. Other way to say it: your happines depend of the amount of success relations you have in your life, with your family or frienships. The food taste better with other people. Is better share than get all the things to you alone. Raise to top is depressant, raise to top togheter is wonderful. This is the reasone because start ups give stock options.`
    ]
  ]
]
