export const DATA_TO_SHOW = [
  [
    "content",
    [
      `Advices from Ricardo Weder: `,
      `1) The growth is not a success measure, is a risk. With growth you dilute the capital, the attention of the teams and in general the attention of the teams to get the product market fit. So, companies have to be careful with expansion: geographically, business side model, divisions or others.`,
      `2) Is important to work in the culture of the company, especially meritocracy and diversity should be the center of the company. Meritocracy: you will recibe the value you give with no others variables influencing. And diversity: have conversations with different ideas with people with different backgrounds, educations, from where they born from, phylosoficals, ideologies and others. With this diversity the companies can achieve innovation.`,
      `First principles from Ricardo Weder in Jüsto:`,
      `3) Inclusion, diversity, respect, the user is always present, be a company of data driven, allows people that are closer to the problem take decisions about it because they are closer to the problem, try to not be a hierarchical company, everyone know with is their objectiv, give so much context to avoid unnecessary process and rules (because with that the company is faster).`,
      `Reflexion from Ricardo Weber:`,
      `4) The role of CEO and of Founder is overrated because they put the vision but those who make that real are the team, especially the executive team. So, to achieve explosive results those who do companies should surround themselves and hire people more expert than them. Sometimes put more money in some problems by itself will not solve problems, some problems are solved by people who know how to do it. To explain a little bit more what want to say Ricardo when he say "CEO and Founder are overrated" is because they usually get to much credit for the work done from the company to outside, but is the team who make this a reality. Nonetheless the vision of the founders are unique and should be strategically suitable. For the experience of Ricardo, he don't know extraordinaries CEO Founders with a non extraordinarie team that have ben achieve success, but it know extraordinaries team with a non extraordinaries CEO Founders that achieve success. But obvisuly boths are important.`,
      `A question: which things not obvious, counter intuitive are important for a CEO Founder to build an high impact team, to be ideal in his role? This not consider the usual thing about relisience for example. From Ricardo Weder he think: beyond the obvious like pasion, be transparent with your motivation and this is the important thing, some grade of naivety (if you know all the complexity of something in advance, before the experience maybe people will not start companies at first place). This should be balanced with the people who know more than you (mentors, the team itself) to reinforce your week areas. Be transparent, humble and reduce the ego of yourself to achieve that is something important.`,
      `A question derivated from the last one: how to found the product market fit (this is, in simple words, is something that people want, that is so necessary that his growth is guaranteed because his quality. Example: iPhone, Internet)? From Ricardo Weder: this always have a part of luck and timing, but what we can control is have a conceptual estrategy very clear, a real understanding of the business itself and market. Other thing: learn how to attract, lead and motivate correct people and with this secure a eficient operation. With the Product Market Fit is always start with the beta more beta of the product and start to communicate with the user, it opens all the channels of comunications to iterate with the feedback of the users. For example, you can believe you have a good product market fit but it canot be, so you have to iterate and incorporate the feedback of users. The product market fit can change heavily with the same product in different population.`,
      `A question derivated from the last one: which error some CEO Founders face when they want to achieve a Product Market Fit? From Ricardo Weder they saw that the mayor problem is the priorization, the use energy, time and attention to things that right now are not important. So the question with this is how CEO Founder can know when they are priorizating things that are not important? The question to answer here is: which are the minimum thing to achieve (clear objective) and what generate more Product Market Fit? For example, some team make so much effort to the brand or communication but at the end the product service is the most important. Other common mistakes, some founders don't want to change their ideas, they don't want to try other things because they think that being an entrepreneur is being attached to their idea. CEO Founders can be attached with the objective but they have to see different angles to keep advancing. Also, other ideas need resources at the beginning in this can be a serious problem and the reason because they don't achieve success.`,
      `A question: Measure the success of a company by the amount of people inside is incorrect. For example, whatsapp, they was less than twenty people before be sold to facebook. The same with Instagram, twenty or thirty persons. It's possible to do big things with small teams. In opposite, for big companies, every new person takes from the Founder from te CEO their time, because when you are in leadership positions your team is not yours anymore, is from your team. This means: more people, less time for leaders. And here, for startups, maybe there's a thing that books are not seeing by the Survivorship Bias: books are writer by people that achieve success, the survivors, and sometimes they confuse the luck with operability (is the difference between: "we did this and it worked for us" versus "we did this and it will work for you"). So, the question here is: when companies get bigger and bigger, the leader can improve their executive layer but more and more is very costly make more and bigger things from the human perspective. In addition to this, sometimes in the company human catastrophes happen: people died or their loved ones died, people get burn out and quit (therefore all your plans banish from one moment to other), some markets that existed now no longer exist, and all of this happen at the same time in middle of personal and/or global crisis of any type. So, how do you growth the company in the middle of apocalypse? From the perspective of Ricardo Weder, they said: "Maybe is a cliche but have a solid culture will help to growth, this means the people inside the company have a clear principles and clear context you will not need to create solid structures of management to control all the teams. One of the biggest challenge for who create and leader companies when they growth is how to let it go the responsibilities maybe because no one is ready to take it and in other moments the same leader is unsecure or have fear to give that responsibility to other person. Other advice here is have time to do nothing, to think, to just be. Some times the best work you can do is take a rest and do nothing and think, without activity. Other advice is learn to say «no» to the things that are not important, this advice is useful in any part of the process with any size in the company".`,
      `A question from the last one: How do you decide which things to say "no" to? From the perspective of Ricardo Weder he say: "It depends if that task takes me time from my family or from the company itself. The thing here is prioritize the things needs the team rather the needs of the leader itself, this with the perspective of the middle and long term. This because if something it needs the team, will have a bigger impact in the company. Always keep in mind that this is not a rule of thumb, every person have to make this decision case by case".`,
      `A question: which things does the Founders believe are important but in the long term are absolutely irrelevant? From Ricardo Weder perspective: "This depend of the business evolution, some business growth so much than overcome the capabilities of the Founder and at that point they have to play other role. Some Founder don't take a step aside to play that other role and leave other person lead the company. No one in a company should be irreplacable, by culture, even the Founder. Founders are vital in early stages but at some point it's good to do other things. This cost so much because companies are the baby of every Founder, but it something to keep in mind. The thing here is keep adding value to the company, maybe at some point in other role Founders can keep bring it value to the company and keep beeing relevant for the company. The thing here is Founder canot be the center all the time".`,
      `A question: one of the biggest difficult thing that happen when you start to growth is the hiring of executive talent. This are the Chief's Officer: Chief Technical Officer, Chief Marketing Officer, Chief Financial Officer, Vice president of Enginnier, of Marketing, of Human Talent, of Operations. This is a process of inversion because you convince them to invest their time in your company and the balance of power is very different from any other type or hiring. So, te question here is: how to found the best talent starting from below to the top? From Ricardo Weder prespective: "Depending of the field you will need a different approach. First is found people who gets motivated with the purpose of the company. This is not passion (it will be very rare and dificcult that anyone have passion from the purpose of the company from the day one). Be very clear about the principles. Is a mistake hire people that fit in the culture of the company, on the contrary you should hire people for the contributions to your culture. The risk of fit in the culture is that people will be a echo: if someone say something stupid they will repeat the same stupidity and everyone will think that is okay. It depends also of the stage of the company, at the beggining companies need flexible people and generalists because is very variable week a week where they have to put the attention, where to put the resources. When the company grows, specialists are required to do something more sophisticated"`,
      `A question: to make big things you must have the best talent, even is there is nothing yet. The question: how this can be done? Convincing in transparent and empatic way of the dream, of the vision of the company, of what you want to build making a speech that touch in a emotional way to that person. It's also important to know how to raise capital. The thing here is convince person who are already senior, give good stock options. This is difficult because when the company has zero capital the stock options have a value of zero too.`,
      `Different start up don't compete between them until they make a high saturation of the market. Remember CEO and Founders live thinking in the future. At some point, when start up start to have an explosive growth will face growth brakes, so in those pivotal moments, if the company overcome that, will have a competitive advatages where any other player will be able to compite at the same level. From Ricardo Weder they say: you have to be aware of your biggest competitor and have an strategy to compete in an disadvantage position (because the money, because the marketing, because the talent, because anything).`,
      `A question: in Latin America, the software companies growth for external factors, like penetration of internet (more people conected, more people will found the company). This don't happen in countries where the internet penetrarion will be very low in the next years because they have already a high penetration of internet. Other example of external growth in Latin America: map of iPhones have a 3D shape and not only a 2D shape. So, that little advantage can improve a little the experience and be more intuitive to the user found a service. The question here is: which external factors in your environment will help to improve your company? This can be of the technology, cultural changes or others factors.`,
      `A question to Ricardo Weder: which advice you will give to who want to rise capital, how do you transmit the opportunity to who want to invest in your company? From Ricardo Weder, he said that the personal and profesional history help, the luck help but to talk about what people can do: define with so much clarity what you will going to do and how you will achieve that. Another one: it's always more interest a bigger market, because as a early investor you don't think of lineal growth, you think that from 30 invest you have, at least 1 will worth all the invests. Another one: have very clear which is the type of people you want to work and know which one exactly. Another: have a very clear financial perspective to transmit that to investors, how much margin you will have and any other important financial measure investors should have to know on the actual state of the company and specially those measures that make sense for the growth of the future.`,
      `Internet is the equalizer most powerful that humanity has built.`
    ]
  ]
]
