export const DATA_TO_DISPLAY = [
  {
    title: "The harsh reality of founding and leading a startup | The story of Freddy Vega",
    source: {
      title: "La dura realidad de fundar y dirigir una Startup | La historia de Freddy Vega",
      url: "https://youtu.be/jQ19FCO4MYA"
    },
    theData: {
      introduction: "",
      title2: "",
      title2: ""
    }
  },
  {
    title: "The truths of having a Startup",
    source: {
      title: "Las verdades de tener una Startup",
      url: "https://youtu.be/Xva1aODyG1w"
    },
    theData: {
      introduction: "",
      title2: "",
      title2: ""
    }
  },
  {
    title: "What CEOs of startups need to know",
    source: {
      title: "Qué necesitan saber los CEO de startups",
      url: "https://youtu.be/x0SiT9Eukrs"
    },
    theData: {
      introduction: "",
      title2: "",
      title2: ""
    }
  },
  {
    title: "How to find your co-founder (Don't start alone!)",
    source: {
      title: "Cómo encontrar a tu cofundador ( No emprendas solo! )",
      url: "https://youtu.be/_kVMSexFIeg"
    },
    theData: {
      introduction: "",
      title2: "",
      title2: ""
    }
  },
  {
    title: "How to be more of a leader and less of a follower",
    source: {
      title: "Cómo ser MÁS LÍDER y menos follower",
      url: "https://youtu.be/uIVFEpenReI"
    },
    theData: {
      introduction: "",
      title2: "",
      title2: ""
    }
  },
  
]