import { DATA_FIVE_CREATED } from "./DATA_FIVE"
import { DATA_FOUR_CREATED } from "./DATA_FOUR"
import { DATA_ONE_CREATED } from "./DATA_ONE"
import { DATA_THREE_CREATED } from "./DATA_THREE"
import { DATA_TWO_CREATED } from "./DATA_TWO"

export const DATA_TO_DISPLAY = [
  DATA_ONE_CREATED,
  DATA_TWO_CREATED,
  DATA_THREE_CREATED,
  DATA_FOUR_CREATED,
  DATA_FIVE_CREATED
]

/* 
!FH
Create all the theData. Think a way to split the information, if is not, this file is going to be huge!

*/
