export const DATA_TO_SHOW = [
  [
    "content",
    [
      `A question: which is your team: the names, the responsabilities and the inner culture of every one?`,
      `A question: in which moment you decide to enter in the field you are right now (or want to be)?`,
      `Some times companies can pay expensive things if they know that it generates benefits. So, sometimes a company can pay 1000 usd dollar at month to certain service but not a 50 dollars at year for other thing. The point here is understand which thing the company understand that is valuable for their business.`,
      `A question: how do you learn to lift capital? Because is possible that you go to some places to talk about your dream and investors don't get interest. For Andrés Sarrazola he said that he read a book call "Venture Deals", make the online course of the same authors. Plus sometimes is more hard to lift capital withouth a reputation then do it when you have ben raised capital before (in the experience of Andrés Sarrazola, was harder to lift 25.000 dollar than 6 million of dollars, because at the beggining he have to convince the other about their dream, while after that the dream is already on rails).`,
      `It is important to have knowledge about not only how to lift capital but also how to use it. Some companies and their members know what to do with 10 or more million of dollars, others companies don't.`,
      `In "Ayenda" the company of Andrés Sarrazola there is a culture of initiation of every person who get hired should accomplish certain metrics and also read certain books in the next two months (is like a test). This depend of the rol, for example in sells the new employee have to read: "Never Split the Difference", "The 10x rule", "Sell or Be Sold"; for more corporative roles the book "The Lean Startup"; for recruiters: "Who". So, in a start up people have to consult the book and the source of knowledge more than one time, because the memory. And after the consulting you will know better what to do. One way to be confident in some field is read books and you can know the quality of the book for Amazon reviews. If you want to learn how to lift capital you can have advice from others that already done that before but for sure there is a minimum of 10 books that already have been writed, which are those 10 books? Read it all and re read it again when you forget something. Same for any other field like recruitment: take advice and read at least 10 good quality books about the topic.`,
      `All this said: it is good to read of certain topic but don't forget about other topics that are related with your life, not only with your business, like quality of sleep "Why we sleep" for example.`,
      `The main objective of "Ayenda" is not to be the best in the field in which they are currently working, it is rather to load the life of each employee in "Ayenda" to be prepared, in the future when things change, to make a quick, smooth and as painless as possible movement towards change. Accomplishing this through disciplined learning and having fun.`,
      `A question to Andrés Sarrazola: which are the biggest learning in all this process of run companies? He said: you will not go wrong in life if you read 4 book at month, in 3 or 4 years you will be in a such better place. Other learn: I really want to work with people better than me, with people who I admire, and this in general for all the Teams in Ayenda. If you hire people that are less than you, you will be finish with less; on the opposite: if you hire people better and bigger than you, you will be finishe bigger and better. The central point is the people.`,
      `Is a lie that business are self crated without help. In reality Founder and CEO share so much information about all the process.`
    ]
  ]
]
