export const DATA_TO_SHOW = [
  [
    "content",
    [
      `José Guillermo Calderón, founder of Robin Food (the so called the first restaurant in the cloud) have to take a decision in pandemic with the almost 15 millions of dollars that he raise for the company to keep growing. The investors said to him the money is for growth not for survive. So, one strategy to not fire anyone was reduce significantly the salary of all the people. This was a voluntary choise that every employee have to do, the plan was: "if we can protect all of us we all can keep going". José Guillermo Calderón was the first person to reduce his salary. There was other things to negociate like the use of spaces for example.`,
      `A question: be resilient is important, but if someone don't have the correct product in the correct time, that doesn't matter. The question here is: how can company growth with the variables against the business model? The company have to change, the company have to expand, what have to do the company? José Guillermo Calderón said for this point something like this: "you have to know the possible future change of your enviornment and how much probable is that happen, of your market, and start to give service for that and be prepare when the market change to that path". In the example of Robin Food they know that in Latin America people will use the "off premis" or "delivery" and the "on premis" or "eat in the sell point" at 50 and 50%, but with the arrive of pandemic this was a 100 and 0% in favor of delivery. After pandemic, this is 65 and 35%. When Robin Food start they difference was 15 and 85% (in favor of "on premis").`,
      `A question: which things are inevitable in your market or in the environment you perform? Maybe something that no one has saw yet. José Guillermo Calderón said to this question: prediction is the key, as Amazon predict the buyer behavior for some dates activating all the supply chain and all things that need to deliver the product in quality and time, the same will apply for the restaurant on premis and off premis. Expensive restaurant already do something like this but with excel spreasheet and intuition of chefs and their own supply chain. This thing is totally different, more acurate and more scalable when you use machine learning, data science and software in general. `,
      `A question: is very important to have awarness with reliable data of the competitors: how much market share the competitor has? What makes your company more valuable in comparison to the others competitors: is cheaper, is faster, other?`,
      `A question: for the things you have accomplish until today in your professional field, which thing or things you never want to do again? José Guillermo Calderón answer this: be a employee for other person.`,
      `A question: what thing you don't want to stop doing it, no matter how much time passes? osé Guillermo Calderón answer this: solve problems.`
    ]
  ]
]
